### ISSUE TITLE
Are you still working on this? Crash after block find

### ISSUE THREAD

**Issue by sigwo** [dbeal-eth/node-merged-pool#2]
I have the barebones stratum running because the server would crash after finding a block (and it doesn't payout to any miner). So I configured and fired up the barebones. To conserve space, the last share, block announcement, and crash are in the hastebin from the barebones stratum crash. 

http://hastebin.com/igorobuyoy.rb

**Comment by cyberbalsa** [comment]
in lib/pool.js line 366

_this.emit('block', options.auxes[aux].symbol, height, hash, tx, res[0].details[0].amount, shareData.difficulty, shareData.worker);

change to 

_this.emit('block', options.auxes[aux].symbol, height, hash, tx, 0, shareData.difficulty, shareData.worker);

Works like a charm
