### ISSUE TITLE
Install issues — shared private keys

### ISSUE THREAD

**Issue by jacobnollette** [dbeal-eth/node-merged-pool#4]
Having issues sharing private keys between separate coins... Any advice for how I can achieve this?

**Comment by jacobnollette** [comment]
It should be important to note, that you can add your mining address to the auxcoin arrays... One payout address is not shared between all coins, but all nodes.. And the demo script doesn't include these variables, which are required.

**Comment by sigwo** [comment]
I'm not following. So your coin.json file looks something like:

{
    "coin": "potcoin.json",
    "auxes": [
        {
            "coin": "syscoin.json",
            "daemons": [
                {
                    "host": "127.0.0.1",
                    "port": 8368,
                    "user": "nompy",
                    "password": "password1234",
                    "address": "SjmuQbxgX6CPekwnwismWYvZCh8MbfcNKR"
                }
            ]
        }
    ],

```
"address": "PRbSC4dimqNcFCaJZb9auk12cXJEyJQwBW",

"rewardRecipients": {
    "962994c187a0b6fb4cb66bbaf520badcfa8dafe4": 0.4,
    "22851477d63a085dbc2398c8430af1c09e7343f6": 0.1
},
```

....rest of config

?

**Comment by jacobnollette** [comment]
almost!

var myCoin = {
    "name": "Dogecoin",
    "symbol": "DOGE",
    "algorithm": "scrypt"
};

var myAuxCoins = [
{
    "name": "Syscoin",
    "symbol": "SYS",
    "algorithm": "scrypt",

```
"address": "sys coin address",

"daemons": [
    { 
        "host": "127.0.0.1",
        "port": 41016, // **NOT ACTUAL PORT**
        "user": "username",
        "password": "passowrd"
    }
],
```

}

];
var pool = Stratum.createPool({
    "coin": myCoin,
    "auxes": myAuxCoins,
    "address": "dogecoin address",

```
"rewardRecipients": {
    "D6dHQrhnzAJdy9aqs1YqS8SnCnYhi1PjCg": 0,
    "22851477d63a085dbc2398c8430af1c09e7343f6": 0.1
},
```

**Comment by jacobnollette** [comment]
question — i've heard that you parent coin needs to have higher difficult than the auxcoins — do you know this to be true? I was mining ruby and sys, and caught a sys coin block right off the bat, so i'm not sure.. Now I'm not getting any blocks for a few hours...

**Comment by sigwo** [comment]
So you are using the *.js for pool configs instead of *.json? Where did you drop that file in the structure to get it to work? Right now, I use potcoin.json (for POT/SYS) and created a /pools/ folder....

 As for the difficulty, that's what I heard.

EDIT: Ah, Yes, when running the non-portal version this is how I did it. I'm a little slow tonight.

**Comment by jacobnollette** [comment]
i'm just running a simple *.js script — haven't integrated things back into a portal or anything more elaborate than a few playing with like two coins. Still searching for other merged coins — google seems to be burying info. 

BTW started getting ruby blocks, but not sys blocks for a long time, so I'm jumping over to test out doge-sys theory.. Doge blocks usually take between 24-36 hours, should get a sys block soon though.

If your up, jump over to #node-merged-pool on free node irc.
